name: Backend_Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: openjdk:25-rc-jdk
      options: --workdir /github/workspace

    defaults:
      run:
        working-directory: ./back_end
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        ./mvnw install -DskipTests
    - name: Build
      run: |
        ./mvnw compile
    - name: Run Tests
      run: |
        ./mvnw test
